/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is the request body used by the HTML form submission for adding a user to a Project.
 */
export interface PersonProjectForm {
  /**
   * Name of the user.
   */
  name: string;
  /**
   * The role the user will have with respect to the Project.
   */
  role: 'owner' | 'member' | 'manager';
  href: string;
  _links?: unknown;
}
